### ISSUE TITLE
Map inconsistency "Solomons"

### ISSUE THREAD

**Issue by panther2** [triplea-maps/domination_1914_no_mans_land#1]
As brought up on A&A.org:

https://www.axisandallies.org/forums/index.php?topic=41124.0

> 1914 NML map has inconsistency:  Guadalcanal, which is part of Solomons, in SZ113 color brown, owned by Bri with brown Bri infantry and Bri flag; and Solomons in SZ121 also color brown, but owned by Ger with gray Ger infantry and Ger flag.  Either Solomon Isl color should change to Ger gray, or the ownership and unit should change to Bri.  Also, it is incorrectly titled Solomon Islar

**Comment by ron-murhammer** [comment]
Yeah, appears there is an issue with the territory boundaries as it is actually owned by Germany but is shown as brown (UK color) instead of gray (German color).

**Comment by ron-murhammer** [comment]
This is now fixed with https://github.com/triplea-maps/domination_1914_no_mans_land/pull/3
